services:
  - type: web
    name: mengmeiyi-sales-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        value: https://nwnawzlrtpiqmeyowzla.supabase.co
      - key: SUPABASE_KEY
        sync: false
